### ISSUE TITLE
skates let's u glitch trough blocks

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/Skates#2]
![2018-09-20_14 29 34](https://user-images.githubusercontent.com/33039934/45818433-0823e100-bce2-11e8-8ef2-911657eafb3b.png)
running against half bloks or sometimes even full blocks with a skate will make u glitch first into them and later up or through them

**Comment by KaruzoDEV** [comment]
Should be fixed.

**Comment by GoodOldJack12** [comment]
Confirm fixed when

**Comment by KaruzoDEV** [comment]
Should be fixed v2
