### ISSUE TITLE
disconnecting with skate in hand will give it back to u on login ( at kadic )

### ISSUE THREAD

**Issue by mattymatty97** [MinecraftReplicaofCodeLyoko/Skates#3]
![2018-09-20_15 51 23](https://user-images.githubusercontent.com/33039934/45823042-11ff1180-bced-11e8-9bbe-11c3a2939a10.png)

**Comment by GoodOldJack12** [comment]
Might be a PRC issue, waiting for @KaruzoDEV to confirm

**Comment by KaruzoDEV** [comment]
Should be fixed.
